branch-defaults:
  develop:
    environment: tnews-dev
  master:
    environment: tnews
  default:
    environment: tnews-dev
global:
  application_name: tnews
  default_ec2_keyname: null
  default_platform: Docker 1.5.0
  default_region: us-west-1
  profile: eb-cli
  sc: git
